version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projet-devops-app
    image: projet-devops:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m

